<?php
class M_input extends CI_Model
{
	function insert($user){
  	$_1 = $this->input->post('1');
	$_2 = $this->input->post('2');
	$_3 = $this->input->post('3');
	$_4 = $this->input->post('4');
	$_5 = $this->input->post('5');
	$_6 = $this->input->post('6');
	$_7 = $this->input->post('7');
	$_8 = $this->input->post('8');
	$_9 = $this->input->post('9');
	$_10 = $this->input->post('10');
	$_11 = $this->input->post('11');
	$_12 = $this->input->post('12');
	$_13 = $this->input->post('13');
	$_14 = $this->input->post('14');
	$_15 = $this->input->post('15');
	$_16 = $this->input->post('16');
	$_17 = $this->input->post('17');
	$_18 = $this->input->post('18');
	$_19 = $this->input->post('19');
	$_20 = $this->input->post('20');
	$_21 = $this->input->post('21');
	$_22 = $this->input->post('22');
	$_23 = $this->input->post('23');
	$_24 = $this->input->post('24');
	$_25 = $this->input->post('25');
	$_26 = $this->input->post('26');
	$_27 = $this->input->post('27');
	$_28 = $this->input->post('28');
	$_29 = $this->input->post('29');
	$_30 = $this->input->post('30');
	$_31 = $this->input->post('31');
	$_32 = $this->input->post('32');
	$_33 = $this->input->post('33');
	$_34 = $this->input->post('34');
	$_35 = $this->input->post('35');
	$_36 = $this->input->post('36');
	$_37 = $this->input->post('37');
	$_38 = $this->input->post('38');
	$_222 = $this->input->post('222');
	$_39 = $this->input->post('39');
	$_40 = $this->input->post('40');
	$_44 = $this->input->post('44');
	$_49 = $this->input->post('49');
	$_50 = $this->input->post('50');
	$_55 = $this->input->post('55');
	$_56 = $this->input->post('56');
	$_61 = $this->input->post('61');
	$_62 = $this->input->post('62');
	$_63 = $this->input->post('63');
	$_64 = $this->input->post('64');
	$_66 = $this->input->post('66');
	$_67 = $this->input->post('67');
	$_69 = $this->input->post('69');
	$_70 = $this->input->post('70');
	$_72 = $this->input->post('72');
	$_73 = $this->input->post('73');
	$_75 = $this->input->post('75');
	$_76 = $this->input->post('76');
	$_78 = $this->input->post('78');
	$_79 = $this->input->post('79');
	$_81 = $this->input->post('81');
	$_82 = $this->input->post('82');
	$_84 = $this->input->post('84');
	$_85 = $this->input->post('85');
	$_87 = $this->input->post('87');
	$_88 = $this->input->post('88');
	$_90 = $this->input->post('90');
	$_91 = $this->input->post('91');
	$_93 = $this->input->post('93');
	$_94 = $this->input->post('94');
	$_95 = $this->input->post('95');
	$_96 = $this->input->post('96');
	$_98 = $this->input->post('98');
	$_100 = $this->input->post('100');
	$_101 = $this->input->post('101');
	$_102 = $this->input->post('102');
	$_103 = $this->input->post('103');
	$_104 = $this->input->post('104');
	$_105 = $this->input->post('105');
	$_106 = $this->input->post('106');
	$_107 = $this->input->post('107');
	$_108 = $this->input->post('108');
	$lokasi = $this->input->post('lokasikegiatan');
	$biaya = $this->input->post('biaya');
	$tanggal = $this->input->post('tanggal_sos');
		$data1 = array(	'update_id'=>$user,
						'mengundang_kepsek'=>$_1,
						'mengundang_guru'=>$_2,
						'mengundang_siswa'=>$_3,
						'mengunjungi_kepsek'=>$_4,
						'mengunjungi_guru'=>$_5,
						'mengunjungi_siswa'=>$_6,
						'media_kepsek'=>$_7,
						'media_guru'=>$_8,
						'media_siswa'=>$_9,
						'leaflet_kepsek'=>$_10,
						'leaflet_guru'=>$_11,
						'leaflet_siswa'=>$_12,
						'baliho_kepsek'=>$_13,
						'baliho_guru'=>$_14,
						'baliho_siswa'=>$_15,
						'tv_kepsek'=>$_16,
						'tv_guru'=>$_17,
						'tv_siswa'=>$_18,
						'radio_kepsek'=>$_19,
						'radio_guru'=>$_20,
						'radio_siswa'=>$_21,
						'lainya_pes'=>$_222,
						'mengundang_jum'=>$_22,
						'mengunjungi_jum'=>$_23,
						'media_jum'=>$_24,
						'leaflet_jum'=>$_25,
						'baliho_jum'=>$_26,
						'tv_jum'=>$_27,
						'radio_jum'=>$_28,
						'lainya_jum'=>$_29,
						'mengundang_lok'=>$_30,
						'mengunjungi_lok'=>$_31,
						'media_lok'=>$_32,
						'leaflet_lok'=>$_33,
						'baliho_lok'=>$_34,
						'tv_lok'=>$_35,
						'radio_lok'=>$_36,
						'lainya_lok'=>$_37,
						'lainya_lainya'=>$_38);
				$data2 = array(
						'update_id'=>$user,
						'status_kepsek'=>$_39,
						'ket_kepsek'=>$_40,
						'status_gurubk'=>$_44,
						'ket_gurubk'=>$_49,
						'status_siswa'=>$_50,
						'ket_siswa'=>$_55,
						'status_ortu'=>$_56,
						'ket_ortu'=>$_61);
				$data3 = array(
						'update_id'=>$user,
						'status_helpdesk'=>$_62,
						'status_telpon'=>$_64,
						'status_sms'=>$_67,
						'status_twitter'=>$_70,
						'status_fb'=>$_73,
						'ket_helpdesk'=>$_63,
						'ket_telpon'=>$_66,
						'ket_sms'=>$_72,
						'ket_twitter'=>$_69,
						'ket_fb'=>$_75);
				$data4 = array(
						'update_id'=>$user,
						'status_koneksi'=>$_76,
						'ket_koneksi'=>$_78,
						'status_npsn'=>$_79,
						'ket_npsn'=>$_81,
						'status_nisn'=>$_82,
						'ket_nisn'=>$_84,
						'status_akreditasi'=>$_85,
						'ket_akreditasi'=>$_87,
						'status_cara'=>$_88,
						'ket_cara'=>$_90,
						'status_kurikulum'=>$_91,
						'ket_kurikulum'=>$_93,
						'lainya'=>$_94);
				$data5 = array(
						'update_id'=>$user,
						'isi'=>$_95);
				$data6 = array(
						'update_id'=>$user,
						'status_keolahragaan'=>$_96,
						'masukan_keolahragaan'=>$_98,
						'status_seni'=>$_100,
						'masukan_seni'=>$_101);
				$data7 = array(
						'update_id'=>$user,
						'siswa'=>$_102,
						'guru_bk'=>$_103,
						'kepsek'=>$_104,
						'ortu'=>$_105);
				$data8 = array(
						'update_id'=>$user,
						'lokasi_sos'=>$lokasi,
						'biaya'=>$biaya,
						'tanggal_sos'=>$tanggal,
						'isi1'=>$_106,
						'isi2'=>$_107,
						'isi3'=>$_108);
				if($user==NULL){ echo ("<SCRIPT LANGUAGE='JavaScript'>window.alert('Data Gagal Di Simpan. Kemungkinan Koneksi bermasalah. Silahkan input  kembali.')
    window.location.href='".base_url()."input';
    </SCRIPT>"); return false;}
				$this->db->insert('t_1',$data1);
				$this->db->insert('t_2',$data2);
				$this->db->insert('t_3',$data3);
				$this->db->insert('t_4',$data4);
				$this->db->insert('t_5',$data5);
				$this->db->insert('portofolio',$data6);
				$this->db->insert('pendaftaran',$data7);
				$this->db->insert('masukan_terpenting',$data8);
 }
 function update($user){
  	$_1 = $this->input->post('1');
	$_2 = $this->input->post('2');
	$_3 = $this->input->post('3');
	$_4 = $this->input->post('4');
	$_5 = $this->input->post('5');
	$_6 = $this->input->post('6');
	$_7 = $this->input->post('7');
	$_8 = $this->input->post('8');
	$_9 = $this->input->post('9');
	$_10 = $this->input->post('10');
	$_11 = $this->input->post('11');
	$_12 = $this->input->post('12');
	$_13 = $this->input->post('13');
	$_14 = $this->input->post('14');
	$_15 = $this->input->post('15');
	$_16 = $this->input->post('16');
	$_17 = $this->input->post('17');
	$_18 = $this->input->post('18');
	$_19 = $this->input->post('19');
	$_20 = $this->input->post('20');
	$_21 = $this->input->post('21');
	$_22 = $this->input->post('22');
	$_23 = $this->input->post('23');
	$_24 = $this->input->post('24');
	$_25 = $this->input->post('25');
	$_26 = $this->input->post('26');
	$_27 = $this->input->post('27');
	$_28 = $this->input->post('28');
	$_29 = $this->input->post('29');
	$_30 = $this->input->post('30');
	$_31 = $this->input->post('31');
	$_32 = $this->input->post('32');
	$_33 = $this->input->post('33');
	$_34 = $this->input->post('34');
	$_35 = $this->input->post('35');
	$_36 = $this->input->post('36');
	$_37 = $this->input->post('37');
	$_38 = $this->input->post('38');
	$_222 = $this->input->post('222');
	$_39 = $this->input->post('39');
	$_40 = $this->input->post('40');
	$_44 = $this->input->post('44');
	$_49 = $this->input->post('49');
	$_50 = $this->input->post('50');
	$_55 = $this->input->post('55');
	$_56 = $this->input->post('56');
	$_61 = $this->input->post('61');
	$_62 = $this->input->post('62');
	$_63 = $this->input->post('63');
	$_64 = $this->input->post('64');
	$_66 = $this->input->post('66');
	$_67 = $this->input->post('67');
	$_69 = $this->input->post('69');
	$_70 = $this->input->post('70');
	$_72 = $this->input->post('72');
	$_73 = $this->input->post('73');
	$_75 = $this->input->post('75');
	$_76 = $this->input->post('76');
	$_78 = $this->input->post('78');
	$_79 = $this->input->post('79');
	$_81 = $this->input->post('81');
	$_82 = $this->input->post('82');
	$_84 = $this->input->post('84');
	$_85 = $this->input->post('85');
	$_87 = $this->input->post('87');
	$_88 = $this->input->post('88');
	$_90 = $this->input->post('90');
	$_91 = $this->input->post('91');
	$_93 = $this->input->post('93');
	$_94 = $this->input->post('94');
	$_95 = $this->input->post('95');
	$_96 = $this->input->post('96');
	$_98 = $this->input->post('98');
	$_100 = $this->input->post('100');
	$_101 = $this->input->post('101');
	$_102 = $this->input->post('102');
	$_103 = $this->input->post('103');
	$_104 = $this->input->post('104');
	$_105 = $this->input->post('105');
	$_106 = $this->input->post('106');
	$_107 = $this->input->post('107');
	$_108 = $this->input->post('108');
	$lokasi = $this->input->post('lokasikegiatan');
	$biaya = $this->input->post('biaya');
	$tanggal = $this->input->post('tanggal_sos');
		$data1 = array(	'update_id'=>$user,
						'mengundang_kepsek'=>$_1,
						'mengundang_guru'=>$_2,
						'mengundang_siswa'=>$_3,
						'mengunjungi_kepsek'=>$_4,
						'mengunjungi_guru'=>$_5,
						'mengunjungi_siswa'=>$_6,
						'media_kepsek'=>$_7,
						'media_guru'=>$_8,
						'media_siswa'=>$_9,
						'leaflet_kepsek'=>$_10,
						'leaflet_guru'=>$_11,
						'leaflet_siswa'=>$_12,
						'baliho_kepsek'=>$_13,
						'baliho_guru'=>$_14,
						'baliho_siswa'=>$_15,
						'tv_kepsek'=>$_16,
						'tv_guru'=>$_17,
						'tv_siswa'=>$_18,
						'radio_kepsek'=>$_19,
						'radio_guru'=>$_20,
						'radio_siswa'=>$_21,
						'lainya_pes'=>$_222,
						'mengundang_jum'=>$_22,
						'mengunjungi_jum'=>$_23,
						'media_jum'=>$_24,
						'leaflet_jum'=>$_25,
						'baliho_jum'=>$_26,
						'tv_jum'=>$_27,
						'radio_jum'=>$_28,
						'lainya_jum'=>$_29,
						'mengundang_lok'=>$_30,
						'mengunjungi_lok'=>$_31,
						'media_lok'=>$_32,
						'leaflet_lok'=>$_33,
						'baliho_lok'=>$_34,
						'tv_lok'=>$_35,
						'radio_lok'=>$_36,
						'lainya_lok'=>$_37,
						'lainya_lainya'=>$_38);
				$data2 = array(
						'update_id'=>$user,
						'status_kepsek'=>$_39,
						'ket_kepsek'=>$_40,
						'status_gurubk'=>$_44,
						'ket_gurubk'=>$_49,
						'status_siswa'=>$_50,
						'ket_siswa'=>$_55,
						'status_ortu'=>$_56,
						'ket_ortu'=>$_61);
				$data3 = array(
						'update_id'=>$user,
						'status_helpdesk'=>$_62,
						'status_telpon'=>$_64,
						'status_sms'=>$_67,
						'status_twitter'=>$_70,
						'status_fb'=>$_73,
						'ket_helpdesk'=>$_63,
						'ket_telpon'=>$_66,
						'ket_sms'=>$_72,
						'ket_twitter'=>$_69,
						'ket_fb'=>$_75);
				$data4 = array(
						'update_id'=>$user,
						'status_koneksi'=>$_76,
						'ket_koneksi'=>$_78,
						'status_npsn'=>$_79,
						'ket_npsn'=>$_81,
						'status_nisn'=>$_82,
						'ket_nisn'=>$_84,
						'status_akreditasi'=>$_85,
						'ket_akreditasi'=>$_87,
						'status_cara'=>$_88,
						'ket_cara'=>$_90,
						'status_kurikulum'=>$_91,
						'ket_kurikulum'=>$_93,
						'lainya'=>$_94);
				$data5 = array(
						'update_id'=>$user,
						'isi'=>$_95);
				$data6 = array(
						'update_id'=>$user,
						'status_keolahragaan'=>$_96,
						'masukan_keolahragaan'=>$_98,
						'status_seni'=>$_100,
						'masukan_seni'=>$_101);
				$data7 = array(
						'update_id'=>$user,
						'siswa'=>$_102,
						'guru_bk'=>$_103,
						'kepsek'=>$_104,
						'ortu'=>$_105);
				$data8 = array(
						'update_id'=>$user,
						'lokasi_sos'=>$lokasi,
						'biaya'=>$biaya,
						'tanggal_sos'=>$tanggal,
						'isi1'=>$_106,
						'isi2'=>$_107,
						'isi3'=>$_108);
				$this->db->where('update_id',$user);
				$this->db->update('t_1',$data1);
				$this->db->where('update_id',$user);
				$this->db->update('t_2',$data2);
				$this->db->where('update_id',$user);
				$this->db->update('t_3',$data3);
				$this->db->where('update_id',$user);
				$this->db->update('t_4',$data4);
				$this->db->where('update_id',$user);
				$this->db->update('t_5',$data5);
				$this->db->where('update_id',$user);
				$this->db->update('portofolio',$data6);
				$this->db->where('update_id',$user);
				$this->db->update('pendaftaran',$data7);
				$this->db->where('update_id',$user);
				$this->db->update('masukan_terpenting',$data8);
 }
}